/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_joesmate_general_utils_tools */

#ifndef _Included_com_joesmate_general_utils_tools
#define _Included_com_joesmate_general_utils_tools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_joesmate_general_utils_tools
 * Method:    asc_hex
 * Signature: ([B[BI)I
 */
JNIEXPORT jint JNICALL Java_com_joesmate_general_utils_tools_asc_1hex
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint);

/*
 * Class:     com_joesmate_general_utils_tools
 * Method:    hex_split
 * Signature: ([BI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_joesmate_general_utils_tools_hex_1split
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_joesmate_general_utils_tools
 * Method:    hexStringToBytes
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_joesmate_general_utils_tools_hexStringToBytes
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
